# Generated by Django 5.2.3 on 2025-06-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_dot_art'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotArtEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot_art_string', models.CharField(max_length=225, unique=True)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
